<option value="" selected="selected">——</option>
<option value="ab">Abkhazian</option>
<option value="ace">Achinese</option>
<option value="ach">Acoli</option>
<option value="ada">Adangme</option>
<option value="ady">Adyghe</option>
<option value="aa">Afar</option>
<option value="afh">Afrihili</option>
<option value="af">Afrikaans</option>
<option value="afa">Afro-Asiatic languages</option>
<option value="ain">Ainu</option>
<option value="ak">Akan</option>
<option value="akk">Akkadian</option>
<option value="sq">Albanian</option>
<option value="ale">Aleut</option>
<option value="alg">Algonquian languages</option>
<option value="tut">Altaic languages</option>
<option value="am">Amharic</option>
<option value="anp">Angika</option>
<option value="apa">Apache languages</option>
<option value="ar">Arabic</option>
<option value="an">Aragonese</option>
<option value="arp">Arapaho</option>
<option value="arw">Arawak</option>
<option value="hy">Armenian</option>
<option value="rup">Aromanian</option>
<option value="art">Artificial languages</option>
<option value="as">Assamese</option>
<option value="ast">Asturian</option>
<option value="ath">Athapascan languages</option>
<option value="aus">Australian languages</option>
<option value="map">Austronesian languages</option>
<option value="av">Avaric</option>
<option value="ae">Avestan</option>
<option value="awa">Awadhi</option>
<option value="ay">Aymara</option>
<option value="az">Azerbaijani</option>
<option value="ban">Balinese</option>
<option value="bat">Baltic languages</option>
<option value="bal">Baluchi</option>
<option value="bm">Bambara</option>
<option value="bai">Bamileke languages</option>
<option value="bad">Banda languages</option>
<option value="bnt">Bantu (Other)</option>
<option value="bas">Basa</option>
<option value="ba">Bashkir</option>
<option value="eu">Basque</option>
<option value="btk">Batak languages</option>
<option value="bej">Beja</option>
<option value="be">Belarusian</option>
<option value="bem">Bemba</option>
<option value="bn">Bengali</option>
<option value="ber">Berber languages</option>
<option value="bho">Bhojpuri</option>
<option value="bh">Bihari languages</option>
<option value="bik">Bikol</option>
<option value="bin">Bini</option>
<option value="bi">Bislama</option>
<option value="byn">Blin</option>
<option value="zbl">Blissymbols</option>
<option value="nb">Bokm?l, Norwegian</option>
<option value="bs">Bosnian</option>
<option value="bra">Braj</option>
<option value="br">Breton</option>
<option value="bug">Buginese</option>
<option value="bg">Bulgarian</option>
<option value="bua">Buriat</option>
<option value="my">Burmese</option>
<option value="cad">Caddo</option>
<option value="ca">Catalan</option>
<option value="cau">Caucasian languages</option>
<option value="ceb">Cebuano</option>
<option value="cel">Celtic languages</option>
<option value="cai">Central American Indian languages</option>
<option value="km">Central Khmer</option>
<option value="chg">Chagatai</option>
<option value="cmc">Chamic languages</option>
<option value="ch">Chamorro</option>
<option value="ce">Chechen</option>
<option value="chr">Cherokee</option>
<option value="chy">Cheyenne</option>
<option value="chb">Chibcha</option>
<option value="ny">Chichewa</option>
<option value="zh">Chinese</option>
<option value="chn">Chinook jargon</option>
<option value="chp">Chipewyan</option>
<option value="cho">Choctaw</option>
<option value="cu">Church Slavic</option>
<option value="chk">Chuukese</option>
<option value="cv">Chuvash</option>
<option value="nwc">Classical Newari</option>
<option value="syc">Classical Syriac</option>
<option value="cop">Coptic</option>
<option value="kw">Cornish</option>
<option value="co">Corsican</option>
<option value="cr">Cree</option>
<option value="mus">Creek</option>
<option value="crp">Creoles and pidgins</option>
<option value="cpe">Creoles and pidgins, English based</option>
<option value="cpf">Creoles and pidgins, French-based</option>
<option value="cpp">Creoles and pidgins, Portuguese-based</option>
<option value="crh">Crimean Tatar</option>
<option value="hr">Croatian</option>
<option value="cus">Cushitic languages</option>
<option value="cs">Czech</option>
<option value="dak">Dakota</option>
<option value="da">Danish</option>
<option value="dar">Dargwa</option>
<option value="del">Delaware</option>
<option value="din">Dinka</option>
<option value="dv">Divehi</option>
<option value="doi">Dogri</option>
<option value="dgr">Dogrib</option>
<option value="dra">Dravidian languages</option>
<option value="dua">Duala</option>
<option value="nl">Dutch</option>
<option value="dum">Dutch, Middle (ca.1050-1350)</option>
<option value="dyu">Dyula</option>
<option value="dz">Dzongkha</option>
<option value="frs">Eastern Frisian</option>
<option value="efi">Efik</option>
<option value="egy">Egyptian (Ancient)</option>
<option value="eka">Ekajuk</option>
<option value="elx">Elamite</option>
<option value="en">English</option>
<option value="enm">English, Middle (1100-1500)</option>
<option value="ang">English, Old (ca.450-1100)</option>
<option value="myv">Erzya</option>
<option value="eo">Esperanto</option>
<option value="et">Estonian</option>
<option value="ee">Ewe</option>
<option value="ewo">Ewondo</option>
<option value="fan">Fang</option>
<option value="fat">Fanti</option>
<option value="fo">Faroese</option>
<option value="fj">Fijian</option>
<option value="fil">Filipino</option>
<option value="fi">Finnish</option>
<option value="fiu">Finno-Ugrian languages</option>
<option value="fon">Fon</option>
<option value="fr">French</option>
<option value="frm">French, Middle (ca.1400-1600)</option>
<option value="fro">French, Old (842-ca.1400)</option>
<option value="fur">Friulian</option>
<option value="ff">Fulah</option>
<option value="gaa">Ga</option>
<option value="gd">Gaelic</option>
<option value="car">Galibi Carib</option>
<option value="gl">Galician</option>
<option value="lg">Ganda</option>
<option value="gay">Gayo</option>
<option value="gba">Gbaya</option>
<option value="gez">Geez</option>
<option value="ka">Georgian</option>
<option value="de">German</option>
<option value="gmh">German, Middle High (ca.1050-1500)</option>
<option value="goh">German, Old High (ca.750-1050)</option>
<option value="gem">Germanic languages</option>
<option value="gil">Gilbertese</option>
<option value="gon">Gondi</option>
<option value="gor">Gorontalo</option>
<option value="got">Gothic</option>
<option value="grb">Grebo</option>
<option value="grc">Greek, Ancient (to 1453)</option>
<option value="el">Greek, Modern (1453-)</option>
<option value="gn">Guarani</option>
<option value="gu">Gujarati</option>
<option value="gwi">Gwich&#39;in</option>
<option value="hai">Haida</option>
<option value="ht">Haitian</option>
<option value="ha">Hausa</option>
<option value="haw">Hawaiian</option>
<option value="he">Hebrew</option>
<option value="hz">Herero</option>
<option value="hil">Hiligaynon</option>
<option value="him">Himachali languages</option>
<option value="hi">Hindi</option>
<option value="ho">Hiri Motu</option>
<option value="hit">Hittite</option>
<option value="hmn">Hmong</option>
<option value="hu">Hungarian</option>
<option value="hup">Hupa</option>
<option value="iba">Iban</option>
<option value="is">Icelandic</option>
<option value="io">Ido</option>
<option value="ig">Igbo</option>
<option value="ijo">Ijo languages</option>
<option value="ilo">Iloko</option>
<option value="smn">Inari Sami</option>
<option value="inc">Indic languages</option>
<option value="ine">Indo-European languages</option>
<option value="id">Indonesian</option>
<option value="inh">Ingush</option>
<option value="ia">Interlingua</option>
<option value="ie">Interlingue</option>
<option value="iu">Inuktitut</option>
<option value="ik">Inupiaq</option>
<option value="ira">Iranian languages</option>
<option value="ga">Irish</option>
<option value="mga">Irish, Middle (900-1200)</option>
<option value="sga">Irish, Old (to 900)</option>
<option value="iro">Iroquoian languages</option>
<option value="it">Italian</option>
<option value="ja">Japanese</option>
<option value="jv">Javanese</option>
<option value="jrb">Judeo-Arabic</option>
<option value="jpr">Judeo-Persian</option>
<option value="kbd">Kabardian</option>
<option value="kab">Kabyle</option>
<option value="kac">Kachin</option>
<option value="kl">Kalaallisut</option>
<option value="xal">Kalmyk</option>
<option value="kam">Kamba</option>
<option value="kn">Kannada</option>
<option value="kr">Kanuri</option>
<option value="kaa">Kara-Kalpak</option>
<option value="krc">Karachay-Balkar</option>
<option value="krl">Karelian</option>
<option value="kar">Karen languages</option>
<option value="ks">Kashmiri</option>
<option value="csb">Kashubian</option>
<option value="kaw">Kawi</option>
<option value="kk">Kazakh</option>
<option value="kha">Khasi</option>
<option value="khi">Khoisan languages</option>
<option value="kho">Khotanese</option>
<option value="ki">Kikuyu</option>
<option value="kmb">Kimbundu</option>
<option value="rw">Kinyarwanda</option>
<option value="ky">Kirghiz</option>
<option value="tlh">Klingon</option>
<option value="kv">Komi</option>
<option value="kg">Kongo</option>
<option value="kok">Konkani</option>
<option value="ko">Korean</option>
<option value="kos">Kosraean</option>
<option value="kpe">Kpelle</option>
<option value="kro">Kru languages</option>
<option value="kj">Kuanyama</option>
<option value="kum">Kumyk</option>
<option value="ku">Kurdish</option>
<option value="kru">Kurukh</option>
<option value="kut">Kutenai</option>
<option value="lad">Ladino</option>
<option value="lah">Lahnda</option>
<option value="lam">Lamba</option>
<option value="day">Land Dayak languages</option>
<option value="lo">Lao</option>
<option value="la">Latin</option>
<option value="lv">Latvian</option>
<option value="lez">Lezghian</option>
<option value="li">Limburgan</option>
<option value="ln">Lingala</option>
<option value="lt">Lithuanian</option>
<option value="jbo">Lojban</option>
<option value="nds">Low German</option>
<option value="dsb">Lower Sorbian</option>
<option value="loz">Lozi</option>
<option value="lu">Luba-Katanga</option>
<option value="lua">Luba-Lulua</option>
<option value="lui">Luiseno</option>
<option value="smj">Lule Sami</option>
<option value="lun">Lunda</option>
<option value="luo">Luo (Kenya and Tanzania)</option>
<option value="lus">Lushai</option>
<option value="lb">Luxembourgish</option>
<option value="mk">Macedonian</option>
<option value="mad">Madurese</option>
<option value="mag">Magahi</option>
<option value="mai">Maithili</option>
<option value="mak">Makasar</option>
<option value="mg">Malagasy</option>
<option value="ms">Malay</option>
<option value="ml">Malayalam</option>
<option value="mt">Maltese</option>
<option value="mnc">Manchu</option>
<option value="mdr">Mandar</option>
<option value="man">Mandingo</option>
<option value="mni">Manipuri</option>
<option value="mno">Manobo languages</option>
<option value="gv">Manx</option>
<option value="mi">Maori</option>
<option value="arn">Mapudungun</option>
<option value="mr">Marathi</option>
<option value="chm">Mari</option>
<option value="mh">Marshallese</option>
<option value="mwr">Marwari</option>
<option value="mas">Masai</option>
<option value="myn">Mayan languages</option>
<option value="men">Mende</option>
<option value="mic">Mi&#39;kmaq</option>
<option value="min">Minangkabau</option>
<option value="mwl">Mirandese</option>
<option value="moh">Mohawk</option>
<option value="mdf">Moksha</option>
<option value="mkh">Mon-Khmer languages</option>
<option value="lol">Mongo</option>
<option value="mn">Mongolian</option>
<option value="mos">Mossi</option>
<option value="mul">Multiple languages</option>
<option value="mun">Munda languages</option>
<option value="nqo">N&#39;Ko</option>
<option value="nah">Nahuatl languages</option>
<option value="na">Nauru</option>
<option value="nv">Navajo</option>
<option value="nd">Ndebele, North</option>
<option value="nr">Ndebele, South</option>
<option value="ng">Ndonga</option>
<option value="nap">Neapolitan</option>
<option value="new">Nepal Bhasa</option>
<option value="ne">Nepali</option>
<option value="nia">Nias</option>
<option value="nic">Niger-Kordofanian languages</option>
<option value="ssa">Nilo-Saharan languages</option>
<option value="niu">Niuean</option>
<option value="zxx">No linguistic content</option>
<option value="nog">Nogai</option>
<option value="non">Norse, Old</option>
<option value="nai">North American Indian languages</option>
<option value="frr">Northern Frisian</option>
<option value="se">Northern Sami</option>
<option value="no">Norwegian</option>
<option value="nn">Norwegian Nynorsk</option>
<option value="nub">Nubian languages</option>
<option value="nym">Nyamwezi</option>
<option value="nyn">Nyankole</option>
<option value="nyo">Nyoro</option>
<option value="nzi">Nzima</option>
<option value="oc">Occitan (post 1500)</option>
<option value="arc">Official Aramaic (700-300 BCE)</option>
<option value="oj">Ojibwa</option>
<option value="or">Oriya</option>
<option value="om">Oromo</option>
<option value="osa">Osage</option>
<option value="os">Ossetian</option>
<option value="oto">Otomian languages</option>
<option value="pal">Pahlavi</option>
<option value="pau">Palauan</option>
<option value="pi">Pali</option>
<option value="pam">Pampanga</option>
<option value="pag">Pangasinan</option>
<option value="pa">Panjabi</option>
<option value="pap">Papiamento</option>
<option value="paa">Papuan languages</option>
<option value="nso">Pedi</option>
<option value="fa">Persian</option>
<option value="peo">Persian, Old (ca.600-400 B.C.)</option>
<option value="phi">Philippine languages</option>
<option value="phn">Phoenician</option>
<option value="pon">Pohnpeian</option>
<option value="pl">Polish</option>
<option value="pt">Portuguese</option>
<option value="pra">Prakrit languages</option>
<option value="pro">Proven?al, Old (to 1500)</option>
<option value="ps">Pushto</option>
<option value="qu">Quechua</option>
<option value="raj">Rajasthani</option>
<option value="rap">Rapanui</option>
<option value="rar">Rarotongan</option>
<option value="roa">Romance languages</option>
<option value="ro">Romanian</option>
<option value="rm">Romansh</option>
<option value="rom">Romany</option>
<option value="rn">Rundi</option>
<option value="ru">Russian</option>
<option value="sal">Salishan languages</option>
<option value="sam">Samaritan Aramaic</option>
<option value="smi">Sami languages</option>
<option value="sm">Samoan</option>
<option value="sad">Sandawe</option>
<option value="sg">Sango</option>
<option value="sa">Sanskrit</option>
<option value="sat">Santali</option>
<option value="sc">Sardinian</option>
<option value="sas">Sasak</option>
<option value="sco">Scots</option>
<option value="sel">Selkup</option>
<option value="sem">Semitic languages</option>
<option value="sr">Serbian</option>
<option value="srr">Serer</option>
<option value="shn">Shan</option>
<option value="sn">Shona</option>
<option value="ii">Sichuan Yi</option>
<option value="scn">Sicilian</option>
<option value="sid">Sidamo</option>
<option value="sgn">Sign Languages</option>
<option value="bla">Siksika</option>
<option value="sd">Sindhi</option>
<option value="si">Sinhala</option>
<option value="sit">Sino-Tibetan languages</option>
<option value="sio">Siouan languages</option>
<option value="sms">Skolt Sami</option>
<option value="den">Slave (Athapascan)</option>
<option value="sla">Slavic languages</option>
<option value="sk">Slovak</option>
<option value="sl">Slovenian</option>
<option value="sog">Sogdian</option>
<option value="so">Somali</option>
<option value="son">Songhai languages</option>
<option value="snk">Soninke</option>
<option value="wen">Sorbian languages</option>
<option value="st">Sotho, Southern</option>
<option value="sai">South American Indian (Other)</option>
<option value="alt">Southern Altai</option>
<option value="sma">Southern Sami</option>
<option value="es">Spanish</option>
<option value="srn">Sranan Tongo</option>
<option value="suk">Sukuma</option>
<option value="sux">Sumerian</option>
<option value="su">Sundanese</option>
<option value="sus">Susu</option>
<option value="sw">Swahili</option>
<option value="ss">Swati</option>
<option value="sv">Swedish</option>
<option value="gsw">Swiss German</option>
<option value="syr">Syriac</option>
<option value="tl">Tagalog</option>
<option value="ty">Tahitian</option>
<option value="tai">Tai languages</option>
<option value="tg">Tajik</option>
<option value="tmh">Tamashek</option>
<option value="ta">Tamil</option>
<option value="tt">Tatar</option>
<option value="te">Telugu</option>
<option value="ter">Tereno</option>
<option value="tet">Tetum</option>
<option value="th">Thai</option>
<option value="bo">Tibetan</option>
<option value="tig">Tigre</option>
<option value="ti">Tigrinya</option>
<option value="tem">Timne</option>
<option value="tiv">Tiv</option>
<option value="tli">Tlingit</option>
<option value="tpi">Tok Pisin</option>
<option value="tkl">Tokelau</option>
<option value="tog">Tonga (Nyasa)</option>
<option value="to">Tonga (Tonga Islands)</option>
<option value="tsi">Tsimshian</option>
<option value="ts">Tsonga</option>
<option value="tn">Tswana</option>
<option value="tum">Tumbuka</option>
<option value="tup">Tupi languages</option>
<option value="tr">Turkish</option>
<option value="ota">Turkish, Ottoman (1500-1928)</option>
<option value="tk">Turkmen</option>
<option value="tvl">Tuvalu</option>
<option value="tyv">Tuvinian</option>
<option value="tw">Twi</option>
<option value="udm">Udmurt</option>
<option value="uga">Ugaritic</option>
<option value="ug">Uighur</option>
<option value="uk">Ukrainian</option>
<option value="umb">Umbundu</option>
<option value="mis">Uncoded languages</option>
<option value="und">Undetermined</option>
<option value="hsb">Upper Sorbian</option>
<option value="ur">Urdu</option>
<option value="uz">Uzbek</option>
<option value="vai">Vai</option>
<option value="ve">Venda</option>
<option value="vi">Vietnamese</option>
<option value="vo"> Volapük</option>
<option value="vot">Votic</option>
<option value="wak">Wakashan languages</option>
<option value="wal">Walamo</option>
<option value="wa">Walloon</option>
<option value="war">Waray</option>
<option value="was">Washo</option>
<option value="cy">Welsh</option>
<option value="fy">Western Frisian</option>
<option value="wo">Wolof</option>
<option value="xh">Xhosa</option>
<option value="sah">Yakut</option>
<option value="yao">Yao</option>
<option value="yap">Yapese</option>
<option value="yi">Yiddish</option>
<option value="yo">Yoruba</option>
<option value="ypk">Yupik languages</option>
<option value="znd">Zande languages</option>
<option value="zap">Zapotec</option>
<option value="zza">Zaza</option>
<option value="zen">Zenaga</option>
<option value="za">Zhuang</option>
<option value="zu">Zulu</option>
<option value="zun">Zuni</option>